mv config file

diff --git a/tig/Dockerfile b/tig/Dockerfile
--- a/tig/Dockerfile
+++ b/tig/Dockerfile
@@ -4,21 +4,44 @@ FROM ubuntu:24.04 AS base
 ENV TZ=Asia/Tokyo
 ENV LANG=ja_JP.UTF-8
 
+ENV TELEGRAF_BUCKET=my_bucket
+ENV TELEGRAF_ORG=my_org
+ENV TELEGRAF_TOKEN=my_token
+
+
 RUN <<EOF
 
 apt update
 apt upgrade -y
 
 # install prerequisites
-apt install -y \
+apt install -y --no-install-recommends \
     wget \
     curl \
     gnupg \
-    software-properties-common \
     apt-transport-https \
     supervisor \
-    ca-certificates \
-    inotify-tools \
+    ca-certificates
+
+#
+# add sshd (should run in start.sh)
+#
+apt install -y --no-install-recommends openssh-server
+
+sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
+grep -q '^PermitRootLogin yes' /etc/ssh/sshd_config || echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
+
+sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
+grep -q '^PasswordAuthentication yes' /etc/ssh/sshd_config || echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
+
+sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config
+grep -q '^UsePAM no' /etc/ssh/sshd_config || echo 'UsePAM no' >> /etc/ssh/sshd_config
+
+sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
+grep -q '^PermitEmptyPasswords yes' /etc/ssh/sshd_config || echo 'PermitEmptyPasswords yes' >> /etc/ssh/sshd_config
+
+# username and password should be changed after container started, see start.sh
+
 
 # Clean up
 apt remove -y
@@ -34,41 +57,46 @@ FROM base AS builder
 
 RUN <<EOF
 
-# --- Install InfluxDB 1.x ---
+# --- Install InfluxDB 2.x ---
 wget -qO- https://repos.influxdata.com/influxdb.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
 echo "deb https://repos.influxdata.com/ubuntu jammy stable" | tee /etc/apt/sources.list.d/influxdb.list
-apt update
-apt install -y influxdb
 
-# Create InfluxDB directories
-mkdir -p /var/lib/influxdb /var/log/influxdb
-chown -R influxdb:influxdb /var/lib/influxdb
-chmod -R 755 /var/lib/influxdb
+apt update
+apt install -y --no-install-recommends influxdb2
+
+mkdir -p /var/lib/influxdb2 /var/log/influxdb2
+chown -R influxdb:influxdb /var/lib/influxdb2
+chmod -R 755 /var/lib/influxdb2
+
 
 # --- Install Telegraf ---
 wget -qO- https://repos.influxdata.com/influxdb.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
 echo "deb https://repos.influxdata.com/ubuntu jammy stable" | tee /etc/apt/sources.list.d/telegraf.list
+
 apt update
-apt install -y telegraf
+apt install -y --no-install-recommends telegraf
+
 
 # --- Install Grafana ---
 wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/grafana.gpg > /dev/null
 echo "deb https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
+
 apt update
-apt install -y grafana
+apt install -y --no-install-recommends grafana
 
 chown -R grafana:grafana /var/lib/grafana
 chmod -R 755 /var/lib/grafana
 
-# Create mountpoint directory
-mkdir /config
 
-# Clean up
+# --- Clean up ---
 apt remove -y
 apt autoremove -y
 apt clean
 rm -rf /var/lib/apt/lists/*
 rm -rf /var/lib/cache/*
+
+# Create mountpoint directory
+mkdir /config
 
 EOF
 
@@ -80,16 +108,13 @@ EOF
 # VOLUME /var/lib/influxdb
 # VOLUME /var/lib/grafana
 
-COPY influxdb.conf /etc/influxdb/influxdb.conf
-COPY telegraf.conf /etc/telegraf/telegraf.conf
+COPY cfg/influxdb.conf /etc/influxdb/influxdb.conf
+COPY cfg/telegraf.conf /etc/telegraf/telegraf.conf
+COPY cfg/grafana.ini /etc/grafana/grafana.ini
 
-# Grafanaのデフォルト設定は`/etc/grafana/grafana.ini`。
-# 環境変数で多くの設定を上書き可能。
-# ADMINユーザーとパスワードは環境変数で設定可能だが、ここではSupervisordのスタートスクリプトで設定することにする
-# COPY grafana.ini /etc/grafana/grafana.ini # カスタム設定ファイルがあれば
+COPY cfg/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 
-COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
-
+COPY start.sh /
 
 # Startup command
 CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
